const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const React = require('react');
const ShallowRenderer = require('react-shallow-renderer');
const ts = require('typescript');
const root = path.resolve(__dirname, '..');
const native = Object.fromEntries(['View','Text','Pressable','ScrollView','TextInput','Image','ActivityIndicator','Modal','KeyboardAvoidingView','FlatList'].map(n => [n,n]));
native.Dimensions = {get:()=>({width:393,height:852})};
native.StyleSheet = {create: v => v}; native.Keyboard = {dismiss() {}}; native.Platform = {OS:'ios'};
native.Animated = {View:'Animated.View', Value:class {setValue(){} interpolate(){return 0;}}, timing:()=>({start(){},stop(){}})};
native.AccessibilityInfo = {isReduceMotionEnabled:async()=>false,addEventListener:()=>({remove(){}})};
native.LayoutAnimation = {configureNext(){},Types:{easeInEaseOut:'easeInEaseOut'}};
native.AppState = {currentState:'active',addEventListener:()=>({remove(){}})};
let focus, effects = [], speechListener, reply, apiCalls = [], saved = new Map();
const models = [{id:'configured-a',apiModel:'provider-a',name:'Provider A',provider:'A',providerModel:'actual-a'}, {id:'configured-b',apiModel:'provider-b',name:'Provider B',provider:'B',providerModel:'actual-b'}];
const client = {get:async()=>({data:{success:true,data:models}}),post:async(...args)=>{apiCalls.push(args);return reply();}};
const fakeSpeech = {subscribe:cb=>{speechListener=cb;return {remove(){}};},start:async()=>{},stop(){speechListener({text:'spoken words',final:true});},cancel(){}};
const cache = new Map();
function load(file) {
  if(cache.has(file)) return cache.get(file);
  const mod = new Module(file,module); mod.filename=file; mod.paths=Module._nodeModulePaths(path.dirname(file)); const original=mod.require.bind(mod);
  mod.require=id=>{
    if(id==='react-native') return native;
    if(id==='react-native-safe-area-context') return {SafeAreaView:'SafeAreaView',useSafeAreaInsets:()=>({bottom:20})};
    if(id==='@react-navigation/native') return {useFocusEffect:cb=>{focus=cb;}};
    if(id.endsWith('/client')) return {__esModule:true,default:client,ApiError:Error};
    if(id.endsWith('AuthContext')) return {useAuth:()=>({user:{_id:'test-user',fullName:'Test Learner'}})};
    if(id.endsWith('/storage')) return {storage:{getItem:async key=>saved.get(key)||null,setItem:async(k,v)=>{saved.set(k,v);}}};
    if(id.endsWith('/speechRecognition')) return {speechRecognition:fakeSpeech};
    if(id.endsWith('/clipboard')) return {copyToClipboard(){}};
    if(id.endsWith('.png')) return id;
    if(id.startsWith('.')) for(const ext of ['.ts','.tsx']) {const target=path.resolve(path.dirname(file),id+ext);if(fs.existsSync(target)) return load(target);}
    return original(id);
  };
  mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,file);
  cache.set(file,mod.exports);return mod.exports;
}
function nodes(tree){if(!tree||typeof tree!=='object')return [];if(Array.isArray(tree))return tree.flatMap(nodes);return [tree,...nodes(tree.props?.children)];}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
  const {aiApi}=load(path.join(root,'src/api/aiApi.ts'));
  reply=async()=>({data:{success:true,data:{message:'Actual provider reply'}}});
  const signal=new AbortController().signal;
  await aiApi.chat('question',Array.from({length:25},()=>({role:'assistant',content:'previous'})),'provider-b',signal);
  assert.equal(apiCalls[0][1].history.length,20);assert.equal(apiCalls[0][1].model,'provider-b');assert.equal(apiCalls[0][2].signal,signal);assert.equal(apiCalls[0][2].timeout,90000);
  reply=async()=>{throw Error('offline');}; await assert.rejects(aiApi.chat('hello'),/offline/);
  reply=async()=>({data:{success:true,data:{message:''}}});await assert.rejects(aiApi.chat('hello'),/empty reply/);
  client.get=async()=>({data:{success:true,data:[...models,models[0],{id:'invalid'}]}});
  assert.equal((await aiApi.getModels()).data.length,2);
  client.get=async()=>({data:{success:true,data:[{_id:'1',slug:'writer',name:'Writer',category:{name:'Writing'}},{_id:'2',slug:'writer',name:'Duplicate'},{_id:'3',slug:'disabled',status:'inactive'}]}});
  const tools=(await aiApi.getTools()).data;assert.equal(tools.length,1);assert.equal(tools[0].category,'Writing');
  client.get=async()=>({data:{success:true,data:models}});
  apiCalls=[];
  const originalEffect=React.useEffect;React.useEffect=cb=>effects.push(cb);
  const {AIScreen}=load(path.join(root,'src/screens/ai/AIScreen.tsx'));
  const renderer=new ShallowRenderer();renderer.render(React.createElement(AIScreen,{navigation:{navigate(){}}}));
  const cleanups=effects.slice().map(effect=>effect());const blur=focus();await tick();
  const all=()=>nodes(renderer.getRenderOutput());
  const button=label=>all().find(n=>n.type==='Pressable'&&n.props.accessibilityLabel===label);
  const input=()=>all().find(n=>n.type==='TextInput');
  assert.equal(button('Send message').props.disabled,true);
  assert(!all().some(n=>n.type==='Pressable'&&nodes(n).some(c=>c.props?.children==='Explain AI in simple words')));
  assert(input().props.style.some(style=>style?.height===44),'empty composer is compact');
  input().props.onFocus();
  assert(input().props.style.some(style=>style?.height===46),'focused composer expands');
  input().props.onBlur();
  button('Select AI model, Provider A').props.onPress();
  all().find(n=>n.type==='Pressable'&&nodes(n).some(c=>c.type==='Text'&&c.props.children==='Provider B')).props.onPress();
  input().props.onChangeText('Explain AI');let resolve;
  reply=()=>new Promise(done=>{resolve=done;});button('Send message').props.onPress();button('Send message').props.onPress();
  assert.equal(apiCalls.length,1);assert.equal(apiCalls[0][1].model,'provider-b');
  resolve({data:{success:true,data:{message:'AI learns patterns.'}}});await tick();
  input().props.onChangeText('Give an example');reply=async()=>{throw Error('offline');};button('Send message').props.onPress();await tick();
  assert.equal(apiCalls[1][1].history[1].role,'assistant');
  const userCount=()=>all().filter(n=>n.type==='Text'&&n.props.children==='Give an example').length;
  assert.equal(userCount(),1);
  reply=async()=>({data:{success:true,data:{message:'An example.'}}});
  all().find(n=>n.type==='Pressable'&&nodes(n).some(c=>c.type==='Text'&&c.props.children==='Retry')).props.onPress();await tick();assert.equal(userCount(),1);
  input().props.onChangeText('Draft');button('Dictate message').props.onPress();await tick();speechListener({text:'spoken words',final:true});
  assert.equal(input().props.value,'Draft spoken words');assert.equal(apiCalls.length,3,'dictation never auto-sends');
  button('New chat').props.onPress();assert(!all().some(n=>n.type==='Text'&&n.props.children==='Give an example'));
  button('Chat history').props.onPress();assert(all().some(n=>n.type==='Text'&&n.props.children==='Explain AI'));assert(saved.size);
  input().props.onChangeText('pending');reply=()=>new Promise(()=>{});button('Send message').props.onPress();blur();assert(apiCalls.at(-1)[2].signal.aborted);
  cleanups.forEach(cleanup=>typeof cleanup==='function'&&cleanup());renderer.unmount();React.useEffect=originalEffect;
  const {DashboardOverview}=load(path.join(root,'src/components/DashboardOverview.tsx'));
  const overview=new ShallowRenderer();overview.render(React.createElement(DashboardOverview,{data:{averageProgress:150},courses:[]}));
  assert.equal(nodes(overview.getRenderOutput()).filter(n=>n.type==='Pressable').length,4);
  assert(nodes(overview.getRenderOutput()).some(n=>n.type==='Text'&&n.props.children==='100%'));
  console.log('PASS: real model filtering and selection, request model/history/abort, errors without fake replies, tool deduplication/category mapping, send deduplication, retry, voice-to-editable-draft without auto-send, saved history/new chat, four bounded dashboard cards');
})().catch(error=>{console.error(error);process.exitCode=1;});
