import { Course } from "../types";

export const FALLBACK_COURSES_DATA: Course[] = [
  {
    "_id": "6aa2f695d5d02e7b292269dd",
    "curriculumVersion": "2026-09-10.1",
    "title": "ChatGPT Mastery",
    "slug": "chatgpt-mastery",
    "description": "Learn ChatGPT from your first task to a reviewed practical project. ChatGPT is a conversational assistant that can draft and explain. Treat its reply as a starting point that you can question and refine.",
    "shortDescription": "Write with audience and purpose, create a practical plan and review output before sharing.",
    "order": 0,
    "level": "beginner",
    "category": "AI Chat",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The email is polite, concise and adds no invented offer.",
      "The schedule fits four hours and respects task dependencies.",
      "The final announcement has verified details and no accidental commitments.",
      "Build and review a practical ChatGPT project."
    ],
    "prerequisites": [
      "Access to ChatGPT; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=600&auto=format&fit=crop&q=80",
    "price": 0,
    "isFree": true,
    "tags": [
      "ChatGPT",
      "OpenAI",
      "Prompt Engineering"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:33.203Z",
    "createdAt": "2026-09-10T18:27:33.203Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/chatgpt.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f695d5d02e7b2922689c",
    "curriculumVersion": "2026-09-10.1",
    "title": "Google Gemini AI",
    "slug": "google-gemini-ai",
    "description": "Learn Gemini from your first task to a reviewed practical project. Gemini is Google\u2019s AI assistant for text and supported media tasks. A clear first question is easier to evaluate than a broad request.",
    "shortDescription": "Add context and constraints, extract actions from notes and build a reusable study workflow.",
    "order": 0,
    "level": "beginner",
    "category": "AI Assistant",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The plan fits thirty minutes and includes practical work.",
      "The action list preserves uncertainty and includes only supported commitments.",
      "The session includes the learner\u2019s own reasoning and correction.",
      "Build and review a practical Gemini project."
    ],
    "prerequisites": [
      "Access to Gemini; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    "price": 0,
    "isFree": true,
    "tags": [
      "Gemini",
      "Google AI",
      "Research"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:33.172Z",
    "createdAt": "2026-09-10T18:27:33.172Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/gemini.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f695d5d02e7b2922675b",
    "curriculumVersion": "2026-09-10.1",
    "title": "Zapier AI Automation",
    "slug": "zapier-ai-automation",
    "description": "Learn Zapier from your first task to a reviewed practical project. Zapier connects applications through workflows called Zaps. A trigger detects an event; actions do work in response. Start with test accounts and non-sensitive data.",
    "shortDescription": "Test a trigger before mapping, filter records before acting and publish a controlled workflow.",
    "order": 0,
    "level": "beginner",
    "category": "AI Automation",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The trigger contains the fields that later steps need.",
      "Only explicit consent continues to the next action.",
      "Live runs match the tested behavior and can be stopped safely.",
      "Build and review a practical Zapier project."
    ],
    "prerequisites": [
      "Access to Zapier; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
    "price": 899,
    "isFree": false,
    "tags": [
      "Zapier",
      "Automation",
      "Workflow"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:33.132Z",
    "createdAt": "2026-09-10T18:27:33.132Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/zapier.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f695d5d02e7b2922661a",
    "curriculumVersion": "2026-09-10.1",
    "title": "GitHub Copilot",
    "slug": "github-copilot",
    "description": "Learn GitHub Copilot from your first task to a reviewed practical project. GitHub Copilot offers coding suggestions and chat in supported environments. Use an authorized account and a small repository for first practice.",
    "shortDescription": "Read inline suggestions, generate meaningful tests and prepare a trustworthy review note.",
    "order": 0,
    "level": "beginner",
    "category": "AI Coding",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The helper handles negative values correctly.",
      "The assertions reflect the contract independently of the code.",
      "The review note accurately states the scope and verification.",
      "Build and review a practical GitHub Copilot project."
    ],
    "prerequisites": [
      "Access to GitHub Copilot; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=600&auto=format&fit=crop&q=80",
    "price": 499,
    "isFree": false,
    "tags": [
      "GitHub",
      "Copilot",
      "Coding"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:33.049Z",
    "createdAt": "2026-09-10T18:27:33.049Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/copilot.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b292264d9",
    "curriculumVersion": "2026-09-10.1",
    "title": "Cursor AI Coding Assistant",
    "slug": "cursor-ai-coding-assistant",
    "description": "Learn Cursor from your first task to a reviewed practical project. Cursor is an AI coding environment. Begin in a disposable project or branch so generated changes can be reviewed without risking working software.",
    "shortDescription": "Understand a function with context, implement and inspect a change and review and hand off work.",
    "order": 0,
    "level": "beginner",
    "category": "AI Coding",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The explanation covers actual edge cases rather than invented behavior.",
      "An empty list shows the message without affecting populated lists.",
      "The handoff lists real verification and any remaining limitation.",
      "Build and review a practical Cursor project."
    ],
    "prerequisites": [
      "Access to Cursor; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80",
    "price": 799,
    "isFree": false,
    "tags": [
      "Cursor",
      "Programming",
      "Developer AI"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.950Z",
    "createdAt": "2026-09-10T18:27:32.951Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/cursor.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29226398",
    "curriculumVersion": "2026-09-10.1",
    "title": "Nano Banana AI",
    "slug": "nano-banana-ai",
    "description": "Learn Nano Banana in Gemini from your first task to a reviewed practical project. Nano Banana names Google\u2019s Gemini image-generation and editing family. Use the official Gemini image experience rather than an unrelated look-alike service.",
    "shortDescription": "Make one focused image edit, keep product details intact and download and disclose appropriately.",
    "order": 0,
    "level": "beginner",
    "category": "AI Image",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The mug remains recognizable and the background is changed.",
      "The product details match the original or are corrected before use.",
      "The saved image is usable and does not masquerade as a real installation.",
      "Build and review a practical Nano Banana in Gemini project."
    ],
    "prerequisites": [
      "Access to Nano Banana in Gemini; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80",
    "price": 0,
    "isFree": true,
    "tags": [
      "Nano Banana",
      "Image Editing"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.833Z",
    "createdAt": "2026-09-10T18:27:32.834Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/nano-banana.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29226257",
    "curriculumVersion": "2026-09-10.1",
    "title": "Midjourney AI Image Creation",
    "slug": "midjourney-ai-image-creation",
    "description": "Learn Midjourney from your first task to a reviewed practical project. Midjourney generates images from prompts. It is useful for exploring visual ideas, not for documenting what actually happened.",
    "shortDescription": "Describe subject and composition, use an image as visual input and present concepts responsibly.",
    "order": 0,
    "level": "beginner",
    "category": "AI Image",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The teapot is the visual focus without a cluttered scene.",
      "The result uses the visual direction while matching the new brief.",
      "The moodboard communicates ideas without misleading claims.",
      "Build and review a practical Midjourney project."
    ],
    "prerequisites": [
      "Access to Midjourney; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80",
    "price": 399,
    "isFree": false,
    "tags": [
      "Midjourney",
      "AI Art",
      "Design"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.797Z",
    "createdAt": "2026-09-10T18:27:32.797Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/midjourney.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29226116",
    "curriculumVersion": "2026-09-10.1",
    "title": "Canva AI Design",
    "slug": "canva-ai-design",
    "description": "Learn Canva AI from your first task to a reviewed practical project. Canva combines an editable design canvas with AI assistance. Start with audience and format so the result has a practical destination.",
    "shortDescription": "Draft copy with Magic Write, edit an image carefully and export the right deliverable.",
    "order": 0,
    "level": "beginner",
    "category": "AI Design",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The heading is short and makes no unsupported promise.",
      "The background improves without changing the book\u2019s identity.",
      "The exported image is sharp enough and shows the correct page.",
      "Build and review a practical Canva AI project."
    ],
    "prerequisites": [
      "Access to Canva AI; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&auto=format&fit=crop&q=80",
    "price": 0,
    "isFree": true,
    "tags": [
      "Canva",
      "Magic Design",
      "Graphics"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.764Z",
    "createdAt": "2026-09-10T18:27:32.764Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/canva.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29225fd5",
    "curriculumVersion": "2026-09-10.1",
    "title": "ElevenLabs AI Voice",
    "slug": "elevenlabs-ai-voice",
    "description": "Learn ElevenLabs from your first task to a reviewed practical project. ElevenLabs converts text into speech using selected voices. A clear script and deliberate voice choice are the starting point.",
    "shortDescription": "Write for the ear, handle names and pronunciation and export a finished voiceover.",
    "order": 0,
    "level": "beginner",
    "category": "AI Voice",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The sequence is understandable from audio alone.",
      "The name and time are understandable to the audience.",
      "The voiceover is complete, clear and timed appropriately.",
      "Build and review a practical ElevenLabs project."
    ],
    "prerequisites": [
      "Access to ElevenLabs; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80",
    "price": 399,
    "isFree": false,
    "tags": [
      "ElevenLabs",
      "Voice AI"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.731Z",
    "createdAt": "2026-09-10T18:27:32.731Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/elevenlabs.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29225e94",
    "curriculumVersion": "2026-09-10.1",
    "title": "Runway AI Video Generation",
    "slug": "runway-ai-video-generation",
    "description": "Learn Runway from your first task to a reviewed practical project. Runway offers generative media workflows. Start with a short visual idea and judge motion, not only the opening image.",
    "shortDescription": "Prepare the starting image, design a shot list and deliver a reviewed video.",
    "order": 0,
    "level": "beginner",
    "category": "AI Video",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "Steam changes while the cup remains recognizable.",
      "The sequence is understandable without unexplained visual jumps.",
      "The final files play properly and are presented honestly.",
      "Build and review a practical Runway project."
    ],
    "prerequisites": [
      "Access to Runway; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=600&auto=format&fit=crop&q=80",
    "price": 699,
    "isFree": false,
    "tags": [
      "Runway",
      "Video AI",
      "Creative"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.700Z",
    "createdAt": "2026-09-10T18:27:32.701Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/runway.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29225d53",
    "curriculumVersion": "2026-09-10.1",
    "title": "Perplexity AI Research",
    "slug": "perplexity-ai-research",
    "description": "Learn Perplexity from your first task to a reviewed practical project. Perplexity helps find and synthesize information. Narrow scope gives you sources that can answer a real question.",
    "shortDescription": "Read citations as evidence, research recent changes and write a sourced research brief.",
    "order": 0,
    "level": "beginner",
    "category": "AI Research",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The claim accurately reflects the source\u2019s conditions and measurement.",
      "Planned changes are not described as already active.",
      "Readers can trace each material claim and see remaining uncertainty.",
      "Build and review a practical Perplexity project."
    ],
    "prerequisites": [
      "Access to Perplexity; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&auto=format&fit=crop&q=80",
    "price": 0,
    "isFree": true,
    "tags": [
      "Perplexity",
      "Search AI",
      "Research"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.667Z",
    "createdAt": "2026-09-10T18:27:32.667Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/perplexity.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29225c12",
    "curriculumVersion": "2026-09-10.1",
    "title": "Notion AI Productivity",
    "slug": "notion-ai-productivity",
    "description": "Learn Notion AI from your first task to a reviewed practical project. Notion AI works with writing and knowledge in a workspace. Begin with a private page and a small task you can check.",
    "shortDescription": "Summarize meeting notes, classify feedback with defined labels and build a weekly update page.",
    "order": 0,
    "level": "beginner",
    "category": "Productivity AI",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "Missing owners remain unassigned.",
      "A request for a new feature is not mislabeled as a bug.",
      "The update preserves tentative dates and flags blockers.",
      "Build and review a practical Notion AI project."
    ],
    "prerequisites": [
      "Access to Notion AI; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&auto=format&fit=crop&q=80",
    "price": 0,
    "isFree": true,
    "tags": [
      "Notion",
      "Productivity"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.625Z",
    "createdAt": "2026-09-10T18:27:32.625Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/notion.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29225ad1",
    "curriculumVersion": "2026-09-10.1",
    "title": "Pika AI Video Creator",
    "slug": "pika-ai-video-creator",
    "description": "Learn Pika from your first task to a reviewed practical project. Pika generates short videos from supported prompts and images. Start with one subject and one motion so problems are easy to identify.",
    "shortDescription": "Animate an owned image, create a controlled visual effect and export an honest creative result.",
    "order": 0,
    "level": "beginner",
    "category": "AI Video",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "Leaves move without the gate changing shape dramatically.",
      "The effect is understandable and suitable for the intended audience.",
      "The file plays correctly and its presentation does not mislead viewers.",
      "Build and review a practical Pika project."
    ],
    "prerequisites": [
      "Access to Pika; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80",
    "price": 399,
    "isFree": false,
    "tags": [
      "Pika",
      "Animation",
      "Video AI"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.569Z",
    "createdAt": "2026-09-10T18:27:32.570Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/pika.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f694d5d02e7b29225990",
    "curriculumVersion": "2026-09-10.1",
    "title": "Gamma AI Presentation",
    "slug": "gamma-ai-presentation",
    "description": "Learn Gamma from your first task to a reviewed practical project. Gamma builds presentations from instructions and content. Its cards are sections of a story; decide the audience and desired decision before generating.",
    "shortDescription": "Turn notes into an outline, use purposeful imagery and rehearse a decision-focused story.",
    "order": 0,
    "level": "beginner",
    "category": "AI Productivity",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The outline includes the actual date and venue without new claims.",
      "The visual communicates community without posing as documentary evidence.",
      "A listener can say what decision is requested.",
      "Build and review a practical Gamma project."
    ],
    "prerequisites": [
      "Access to Gamma; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    "price": 0,
    "isFree": true,
    "tags": [
      "Gamma",
      "Presentation AI"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:32.463Z",
    "createdAt": "2026-09-10T18:27:32.463Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/gamma.png",
    "totalLessons": 12
  },
  {
    "_id": "6aa2f693d5d02e7b2922584f",
    "curriculumVersion": "2026-09-10.1",
    "title": "Claude AI Professional",
    "slug": "claude-ai-professional",
    "description": "Learn Claude from your first task to a reviewed practical project. Claude is a conversational assistant for drafting and reasoning. A message supplies instructions; a response is a draft to inspect, not a verified fact.",
    "shortDescription": "Draft a professional follow-up, rewrite without changing meaning and create a repeatable client workflow.",
    "order": 0,
    "level": "beginner",
    "category": "AI Assistant",
    "duration": 226,
    "totalLessonMinutes": 96,
    "totalPracticeMinutes": 120,
    "finalQuizEstimatedMinutes": 10,
    "totalEstimatedMinutes": 226,
    "recommendedMinutesPerDay": 30,
    "durationDays": 1,
    "durationExplanation": "",
    "learningOutcomes": [
      "The email asks for a response without adding a discount or deadline.",
      "The revised text is clearer and retains the date and condition.",
      "The second draft uses only the new client context.",
      "Build and review a practical Claude project."
    ],
    "prerequisites": [
      "Access to Claude; some exercises may require features or credits available on your plan.",
      "Use your own or authorized material. Coding tools require a computer and basic ability to open and run a project."
    ],
    "difficulty": "beginner",
    "thumbnail": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&auto=format&fit=crop&q=80",
    "price": 499,
    "isFree": false,
    "tags": [
      "Claude",
      "Anthropic",
      "AI Writing"
    ],
    "instructor": null,
    "instructorName": "CrackWithAI",
    "status": "published",
    "publishedAt": "2026-09-10T18:27:31.869Z",
    "createdAt": "2026-09-10T18:27:31.871Z",
    "updatedAt": "2026-09-12T18:38:52.205Z",
    "__v": 0,
    "logoUrl": "/assets/course-logos/claude.png",
    "totalLessons": 12
  }
];
